all: 1 2 3 4

1:
	g++ ../tinybind.cpp 1_simple_xml.cpp -o 1_simple_xml
2:
	g++ ../tinybind.cpp 2_svg_parser.cpp -o 2_svg_parser
3:
	g++ ../tinybind.cpp 3_simple_json.cpp -o 3_simple_json
4:
	g++ ../tinybind.cpp 4_xml_to_json.cpp -o 4_xml_to_json
